site:
  title: 天圆地方模组文档
  start_page: doc::index.adoc

content:
  sources:
    - url: .
      branches: v*
      start_path: docs

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    kroki-server-url: https://kroki.io

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable

output:
  dir: public
