:page-title: 土壤含水量
:stem: latexmath
= 土壤含水量

*土壤含水量*，也称 *土壤湿度*，是诸如泥土、草方块等土壤类的方块所具有的特性。土壤含水量的单位是层，最大为 4 层，最小为 0 层（不含水）。

== 计算方式

除耕地使用原版的 moisture 方块属性来存储含水量外，其它的土壤类方块均在原版的基础上拓展了 humidity 方块属性，属性的取值范围为 0~4，直接表示含有多少层水。实际上，humidity 是空气湿度的意思（

对于耕地，可以通过 F3 界面查看其 moisture 属性的值来计算其含水量，计算公式为：

[stem]
++++
\text{含水量（层）}=\text{向下取整}\left(\frac{\text{属性值}+1}{2}\right)
++++

== 机制

=== 最大持水量

土壤拥有一个最大持水量，该值是土壤的特有属性，不会因环境而改变。对于不同种类的土壤，可能有不同的最大持水量。下表列出了每种土壤的最大持水量：

|===
a|*种类*|黏土块|草方块|草径|泥土|砂土|灰化土|沙子|耕地|沙砾
a|*最大持水量*|4|3|3|2|1|1|1|1|0
|===
当土壤含水量没有超过该值时，土壤中的水将不会流动。若降雨、水下渗或其它方式使土壤含水量超过该值，则土壤中的水将会缓慢流动，形成壤中流。在流体物理模式为 MORE_REALITY 时，若土壤侧面或底面裸露，则多余的水有可能会从土壤中渗出，在其它模式下则会消失。模式为 VANNILA 时，若土壤下面一格的方块为炼药锅，则有一定概率填充炼药锅。

对于草方块、草径、泥土、砂土、耕地、灰化土，当其含水量超过该值时，方块会受重力影响而下落。对于沙子，当其含水量恰为该值时，则不会受重力影响。

在配置文件中可以修改上述最大持水量。

=== 蒸发

土壤含水量会影响土壤水的蒸发速度。土壤含水量越大，则蒸发速度越快。

=== 降雨

若流体物理模式为 MORE_REALITY，则当地面（下垫面）的土壤含水量未饱合时，降雨在大多数情况下可以很快下渗而不会在地面形成积水。

== 补充

=== 自然方式

模组会在区块生成时基于生物群系的降雨量给土壤加入一定的含水量，上限为该种土壤的最大持水量。若土壤上方有水，则会忽略上述条件直接给予 4 层的含水量。

下渗可以补充土壤含水量。

土壤水会在土壤间缓慢移动，补充含水量较低的区域，这一过程形成的地下径流叫壤中流。

=== 人为方式

玩家可以手持水瓶点击含水量低于 3 层的土壤以使土壤含水量上升 2 层，该操作对黏土块无效。

在 MORE_REALITY 模式下，用土壤填充水方块时水会优先填充土壤，其次才会往旁边流走。

=== 历史

[cols="^1,6",options="header"]
|===
|版本 ^|更新内容

|0.1
|为草方块、草径、耕地、泥土及其变种、沙子和沙砾加入土壤含水量机制。

|0.1.1
a|
* 为黏土块加入土壤含水量机制
* 草径和耕地在超过最大持水量时会受重力影响
* 现在可以用水瓶润湿土壤
|===